apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-single.fullname" . }}-users
  labels:
    app.kubernetes.io/name: {{ include "clickhouse-single.name" . }}
    helm.sh/chart: {{ include "clickhouse-single.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # users.xml будет смонтирован в контейнер и прочитан ClickHouse.
  # Содержимое генерируем через шаблон и кодируем в base64.
  users.xml: |
    {{- $root := . -}}
    {{- $usersXml := printf "<clickhouse>\n  <users>\n" -}}
    {{- range $u := .Values.clickhouse.users }}
    {{- $networks := $u.networks | default (list "::/0") }}
    {{- $userBlock := printf "    <%s>\n      <password>%s</password>\n      <profile>%s</profile>\n      <quota>%s</quota>\n      <networks>\n" $u.name $u.password (default "default" $u.profile) (default "default" $u.quota) -}}
    {{- range $ip := $networks }}
    {{- $userBlock = printf "%s        <ip>%s</ip>\n" $userBlock $ip -}}
    {{- end }}
    {{- $userBlock = printf "%s      </networks>\n    </%s>\n" $userBlock $u.name -}}
    {{- $usersXml = printf "%s%s" $usersXml $userBlock -}}
    {{- end }}
    {{- $usersXml = printf "%s  </users>\n</clickhouse>\n" $usersXml -}}
    {{- $usersXml | b64enc | nindent 4 }}
